var movie = [
    {
        name:'xxx',
        star:2,
        date:'2015-11-11',
        image:'http://subhd.com/images/back/doctorstrange.jpg',
        // image:'images/2.jpg',
        remark:'qweqwe'
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-12',
        image:'images/2.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3.6,
        date:'2015-11-13',
        image:'images/3.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3.1,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },

    {
        name:'xxx',
        star:3,
        date:'2015-11-11',
        image:'images/1.jpg',
        remark:'qweqwe'
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-12',
        image:'images/2.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-13',
        image:'images/3.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-14',
        image:'images/4.jpg',
        remark:''
    },
    {
        name:'xxx',
        star:3,
        date:'2015-11-15',
        image:'images/5.jpg',
        remark:''
    }

];